### ISSUE TITLE
User able to search food receipt to know how to make food if there is food exist. Otherwise it will shows error message.

### ISSUE THREAD

**Issue by mengyuan1112** [UB-CSE/course-project-teamfit#132]
1, user needs login their account
2, go to home page and type food name in the search bar
3, click Search food ID button to see the list of ID about dish
4, copy any ID from the list and put in to the search bar.
5., click food recipe by ID button
6, and it will show up some recipe about food

**Comment by JQuelen** [comment]
Add Task Tests
