### ISSUE TITLE
Create an AWS account and get familiar with EC2, Python, Cockroach db, React.js

### ISSUE THREAD

**Issue by zayedahm** [UB-CSE/course-project-teamfit#14]
Tests: 
1. Display practical example of a running python unit test 
2. Ssh to EC2 instance
3. Connect to DB and display tables
4. Display simple web UI text using https://codesandbox.io/

**Comment by zayedahm** [comment]
I've created an AWS account and I created a RHEL8 EC2 instance  and I can't find Cockroach DB 

`[root@ip-172-31-5-148 ~]# yum search postgressql
Last metadata expiration check: 0:06:26 ago on Thu 17 Sep 2020 10:05:00 PM UTC.
============================================================ Summary Matched: postgressql ============================================================
rsyslog-pgsql.x86_64 : PostgresSQL support for rsyslog
[root@ip-172-31-5-148 ~]# yum search cockroachdb
Last metadata expiration check: 0:06:33 ago on Thu 17 Sep 2020 10:05:00 PM UTC.
No matches found.
[root@ip-172-31-5-148 ~]# yum search cockroach
Last metadata expiration check: 0:06:38 ago on Thu 17 Sep 2020 10:05:00 PM UTC.
No matches found.
[root@ip-172-31-5-148 ~]# yum search mariadb
Last metadata expiration check: 0:06:47 ago on Thu 17 Sep 2020 10:05:00 PM UTC.
=========================================================== Name Exactly Matched: mariadb ============================================================
mariadb.x86_64 : A very fast and robust SQL database server
========================================================== Name & Summary Matched: mariadb ===========================================================
mariadb-embedded.x86_64 : MariaDB as an embeddable library
mariadb-server.x86_64 : The MariaDB server and related files
mariadb-test.x86_64 : The test suite distributed with MariaDB
mariadb-oqgraph-engine.x86_64 : The Open Query GRAPH engine for MariaDB
mariadb-connector-c.x86_64 : The MariaDB Native Client library (C driver)
mariadb-connector-c.i686 : The MariaDB Native Client library (C driver)
mariadb-devel.x86_64 : Files for development of MariaDB/MySQL applications
mariadb-connector-c-devel.i686 : Development files for mariadb-connector-c
mariadb-connector-c-devel.x86_64 : Development files for mariadb-connector-c
mariadb-connector-odbc.x86_64 : The MariaDB Native Client library (ODBC driver)
mariadb-embedded-devel.x86_64 : Development files for MariaDB as an embeddable library
mariadb-server-utils.x86_64 : Non-essential server utilities for MariaDB/MySQL applications
mariadb-java-client.noarch : Connects applications developed in Java to MariaDB and MySQL databases
=============================================================== Name Matched: mariadb ================================================================
mariadb-common.x86_64 : The shared files required by server and client
mariadb-errmsg.x86_64 : The error messages files required by server and embedded
mariadb-backup.x86_64 : The mariabackup tool for physical online backups
mariadb-gssapi-server.x86_64 : GSSAPI authentication plugin for server
mariadb-server-galera.x86_64 : The configuration files and scripts for galera replication
mariadb-connector-c-config.noarch : Configuration files for packages that use /etc/my.cnf as a configuration file
`

**Comment by zayedahm** [comment]
I was able to install using wget 

`CockroachDB node starting at 2020-09-17 22:39:42.93224342 +0000 UTC (took 0.7s)
build:               CCL v20.1.5 @ 2020/08/24 19:52:08 (go1.13.9)
webui:               http://ip-172-31-5-148.us-east-2.compute.internal:8080
sql:                 postgresql://root@ip-172-31-5-148.us-east-2.compute.internal:26257?sslmode=disable
RPC client flags:    cockroach <client cmd> --host=ip-172-31-5-148.us-east-2.compute.internal:26257 --insecure
logs:                /home/ec2-user/cockroach-data/logs
temp dir:            /home/ec2-user/cockroach-data/cockroach-temp367239979
external I/O path:   /home/ec2-user/cockroach-data/extern
store[0]:            path=/home/ec2-user/cockroach-data
storage engine:      rocksdb
status:              restarted pre-existing node
clusterID:           6fd7e5b0-1fc7-4b81-88b3-20fce3b7650b
nodeID:              1`

**Comment by zayedahm** [comment]
My react.js testing app https://competent-ritchie-ff8b34.netlify.app/

**Comment by aidanrobb** [comment]
![Screenshot 2020-09-27 204101.png](https://images.zenhubusercontent.com/5f5557cda83b5b0edad58ef9/7847925a-1cad-416e-8681-2c57d30599d3)

**Comment by mengyuan1112** [comment]
l create an![Screen Shot 2020-09-27 at 10.22.54 PM.png](https://images.zenhubusercontent.com/5f555518021d8918e4b780c6/eb9ca41e-d29e-4241-9411-d8b8edf0fe86) AWS account

**Comment by mengyuan1112** [comment]
l am about to install DB and display the table for what l insert ![Screen Shot 2020-09-27 at 10.40.57 PM.png](https://images.zenhubusercontent.com/5f555518021d8918e4b780c6/42ef818e-84aa-49d0-9baf-5ca5d3371e85)![Screen Shot 2020-09-27 at 10.42.48 PM.png](https://images.zenhubusercontent.com/5f555518021d8918e4b780c6/89008638-253c-4f54-9cf3-3f320f014fb3)

**Comment by mengyuan1112** [comment]
l learn the python and create the user class

**Comment by mhislam1** [comment]
[image: image.png]
