### ISSUE TITLE
user are able to Register an account

### ISSUE THREAD

**Issue by mengyuan1112** [UB-CSE/course-project-teamfit#43]
1, the user click the register button in the navigation bar.
2, user able type their basic information to register an account.
3, if there is account exisit it will shows "Account already exist" otherwise will shows "Register successful"

**Comment by JQuelen** [comment]
How does a user register for an account? What happens when a user registers for an account? How can a user tell they are logged in? A lot more detail needs to be added to this Task Test

**Comment by mengyuan1112** [comment]
1, the user click the register button in the navigation bar.
2, user able type their basic information to register an account.
3, if there is account exisit it will shows "Account already exist" otherwise will shows "Register successful"
