### ISSUE TITLE
Create profile button in Navbar and initialize the profile page

### ISSUE THREAD

**Issue by zayedahm** [UB-CSE/course-project-teamfit#44]
Testing steps:
1. Clicking on profile button should redirect you to the profile page
2. Profile page should have sections for picture and feed and basic info

**Comment by JQuelen** [comment]
Do all users see the profile page? or just the users that are logged in? Where is the button located? Which pages does the button appear? Add some more detail

**Comment by zayedahm** [comment]
For now everyone could see the profile page, and you don't need to login. The button is located in top of the page, and appears all the time.
