### ISSUE TITLE
Set up Backend to be able to retrieve articles and news on newsfeed from the NewsAPI.

### ISSUE THREAD

**Issue by mhislam1** [UB-CSE/course-project-teamfit#48]

**Comment by JQuelen** [comment]
How is this task accomplished? How can articles and news be stored? Add Task Tests here!

**Comment by mhislam1** [comment]
Hey,

Did you mean add unit tests to test this? I do not understand what you mean
by "here". Please clarify this for me.

- Mohammad

**Comment by JQuelen** [comment]
Every Task requires a Task Test, which shows what this function does and how it should work. you can refer to the template that I made in the Slack a few weeks ago. By "here," I mean in the description of the issue.
