### ISSUE TITLE
As a TeamFit user, I want to have an account to track my health and wellness progress

### ISSUE THREAD

**Issue by aidanrobb** [UB-CSE/course-project-teamfit#6]
1. Go to TeamFit web 
2. login to your own account
3, if user is first time got to web, user can go to register page to register an account
4, if register successful, message will shows "successful register" otherwise shows"Account already exist"
5, after register, user can go to login page to login their account 
6, type in email and password, and click login, it will shows "login successful" otherwise it will shows "password wrong"

**Comment by JQuelen** [comment]
Add a few more steps to this Acceptance Test. Better to have too much detail than not enough
