### ISSUE TITLE
As a TeamFit user I want to be able to send/receive/delete messages

### ISSUE THREAD

**Issue by jgoldverg** [UB-CSE/course-project-teamfit#87]
1. Log in to TeamFit
2. Click on the messages tab
3. Enter your email address
4. There should be 3 forms(create a message, delete a message, list messages)
5. write the user's email in the address bar and a message in the message bar and click send
6. Enter the email address of the user u want to be in the list message form.
7. Enter the messageId of the message you want to delete.

**Comment by JQuelen** [comment]
Make sure to use proper User Story format: "As a -, I want to - so that -."
