### ISSUE TITLE
As a user interested in fitness, I want to keep track of my exercise history so that I can keep track of my health progress

### ISSUE THREAD

**Issue by aidanrobb** [UB-CSE/course-project-teamfit#90]
1. Got to TeamFit website and click 'login' and enter information if you have an account, otherwise register for an account by clicking "sign up". Then click "login here" at bottom of page to log in with newly created account
2. Click on "profile" on the navigation bar after logging in
3. Click "Exercise History" button in your profile
4. To view exercise history, if present, click "show history" button
5. To add to exercise history user can enter time spent on cardio and weights into form 
6. Click "Submit" to add current times to your previous times
7. View these changes by clicking the "show history" button

**Comment by JQuelen** [comment]
Make sure to use proper User Story format: "As a -, I want to - so that -."
