### ISSUE TITLE
As a TeamFit user I want to see my friends' and see suggested friends to follow

### ISSUE THREAD

**Issue by whransom** [UB-CSE/course-project-teamfit#92]
1. Login to TeamFit
2. Click on the Friends tab
3. You should see Friends' pictures in a block to the left like:

Friends:                          
--------------------     
| |Picture| |Picture| |     
| |Picture| |Picture| |      
--------------------

**Comment by JQuelen** [comment]
Make sure to use proper User Story format: "As a -, I want to - so that -."
Also make sure to add dependencies to the User Story
