### ISSUE TITLE
As a TeamFit user I want to be able to login and see my info in the profile page and be able to update my picture, and see fitness and health articles in the homepage, so I would know that I'm logged in and get to read articles related to fitness 

### ISSUE THREAD

**Issue by zayedahm** [UB-CSE/course-project-teamfit#94]
1. Open TeamFit website by opening http://3.23.100.103:3000
2. Register and Login by clicking the login page then sign up 
3. Click on profile, then click refresh to to see your information 
4. Click update image to select new image
5. Image should show up on top of user's info 
4. Click on home page to see fitness and health articles, if news feed is not showing try disabling CORS by installing plug-in "Allow CORS: Access-Control-Allow-origin"

**Comment by JQuelen** [comment]
Make sure to use proper User Story format: "As a __, I want to __ so that __."
