### ISSUE TITLE
As a TeamFit user, I want to post things about health to my profile, so that I can share my thoughts and updates on my profile feed.

### ISSUE THREAD

**Issue by mhislam1** [UB-CSE/course-project-teamfit#95]
1. Log into Teamfit
2. Click on "Profile" tab.
3. Scroll down to see all previous posts as text (if they exist).
4. Type into form and click "Share!" or press enter key. 
5. Refresh page and wait for text to display.
6. Newest post displayed at the top of other posts.

**Comment by JQuelen** [comment]
Make sure to use proper User Story format: "As a -, I want to - so that -."
Also make sure to add dependencies to the User Story
